FROM php:7.2-fpm

# install composer
RUN cd /usr/bin && curl -s http://getcomposer.org/installer | php && ln -s /usr/bin/composer.phar /usr/bin/composer
RUN apt-get update \
 && apt-get install -y \
 git \
 zip \
 unzip \
 vim

RUN apt-get update \
 && apt-get install -y libpq-dev \
 && apt-get install -y libpng-dev \
 && docker-php-ext-install pdo_mysql pdo_pgsql

RUN apt-get install -y gnupg
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get install -y nodejs

WORKDIR /var/www/html